### ISSUE TITLE
Mobile view could do with some love

### ISSUE THREAD

**Issue by ISNIT0** [npmnotes/npmnotes#3]
I think there are two fairly quick wins here:
- Make the navigation pane collapsible (auto-collapse on mobile)
- Make the navigation pane auto re-size/cover the content on mobile

![image](https://user-images.githubusercontent.com/5173131/44290878-bf0be780-a272-11e8-868c-7493dab88cfc.png)
![image](https://user-images.githubusercontent.com/5173131/44290881-c501c880-a272-11e8-9353-9c2ad4fea31e.png)

**Comment by gkutiel** [comment]
I made the layout responsive so that the navigation pane does not appear at all on small devices.
If you think the navigation pane should be also resizable/collapsible please open a new issue about it (it is a low priority right now).

Thank you.
